language: python
python:
  - "3.9"
os:
  - linux
git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/kendryte-freertos-sdk_hello
  - PLATFORMIO_PROJECT_DIR=examples/kendryte-standalone-sdk_hello

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio platform install file://.

script:
  - pio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
