build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/kendryte-freertos-sdk_hello"
    - PLATFORMIO_PROJECT_DIR: "examples/kendryte-standalone-sdk_hello"

platform:
  - x64
install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - cmd: pio platform install https://github.com/OS-Q/P71/archive/qio.zip

build_script:
  - cmd: pio run -d %PLATFORMIO_PROJECT_DIR%

test_script:
  - cmd: qio run -d %PLATFORMIO_PROJECT_DIR%
