build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/kendryte-freertos-sdk_hello"
    - PLATFORMIO_PROJECT_DIR: "examples/kendryte-standalone-sdk_hello"

platform:
  - x64
install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: pio platform install file://.

test_script:
  - cmd: pio run -s -d %PLATFORMIO_PROJECT_DIR%
