name: nightly

on:
  schedule:
    - cron: "0 1 * * *"
# on:
#   push:
#     branches:
#       - master
#       - main

jobs:
  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "kendryte-freertos-sdk_hello"
          - "kendryte-standalone-sdk_hello"
        package: ["master","slave"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install master
        if: matrix.package == 'master'
        run: |
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install file://.

      - name: Install slave
        if: matrix.package == 'slave'
        run: |
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install https://github.com/OS-Q/P71/archive/qio.zip

      - name: Build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

  QIO_fail:
    needs:
      - QIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO build failure"

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "kendryte-freertos-sdk_hello"
          - "kendryte-standalone-sdk_hello"
        package: ["master","slave"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install master
        if: matrix.package == 'master'
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Install slave
        if: matrix.package == 'slave'
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P71/archive/pio.zip

      - name: Build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

  PIO_fail:
    needs:
      - PIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "PIO build failure"
